# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: Timothy Wright
  admin_email: tim@eastbound.io
  admin_password: password
  email_provider_username: <%= ENV["tim@eastboundtech.com"] %>
  email_provider_password: <%= ENV[""] %>
  domain_name: eastboundtech.com
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  stripe_api_key: <%= ENV["sk_test_cjxca0FZVAaViEAnozaQKQ36"] %>
  stripe_publishable_key: <%= ENV["pk_test_c3voM6TBCKSBKYDl8BZHAO7Z"] %>
  secret_key_base: 67d01a8caa792e53339f1068f7ab70aa97e27ab82315a9d90053cca5df338a91100ee9bbd7b0444048b1b8c03f2326460a1799d2b2cc6370270f819b7a7a040d

test:
  domain_name: example.com 
  secret_key_base: 11fda461ebc987d2462645bf634d1d3e49fc102005fdf6e8e29a4275cd67e9be6577f16f6869b01c10977037d7604d8b25db2726dcb9ac9c446c6a2448d5a2ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %> 
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %> 
  stripe_api_key: <%= ENV["sk_live_YmOaMFmYBa3TJQyPA7xbR5yV"] %> 
  stripe_publishable_key: <%= ENV["pk_live_vSmDDYwiXPwoXXonnuE4lIfN"] %> 
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
